linux upstream 2023/12th
sophgocommunity/SG2042-Newsletter pull request #42
Opened 2023-10-12 14:15 UTC by unicornx

2023-10-13 09:12 UTC, XieJiSS requested changes

2023-10-13 09:12 UTC, XieJiSS commented on newsletters/012.md
> +  + After 5 rounds of code review and iteration, preliminary kernel support for Milk-V Pioneer/SG2042 has been merged into [linux-next][lk-1], and it will land the mainline after the merge window of
land on the mainline

> cited from [llvm-dev] OrcV1 removal: ... is ready to land on the mainline.

2023-10-14 00:14 UTC, unicornx commented on newsletters/012.md
> +  + After 5 rounds of code review and iteration, preliminary kernel support for Milk-V Pioneer/SG2042 has been merged into [linux-next][lk-1], and it will land the mainline after the merge window of
Thanks, fixed and re-posted.

2023-10-14 02:25 UTC, XieJiSS approved these changes
LGTM, thanks!

2023-10-14 02:25 UTC, merged