linux-upstream: 2023/17th
sophgocommunity/SG2042-Newsletter pull request #56
Opened 2023-11-17 02:36 UTC by unicornx

2023-11-17 13:09 UTC, XieJiSS requested changes

2023-11-17 13:09 UTC, XieJiSS commented on newsletters/017.md
> +  + [RISC-V: convert SOC_SOPHGO to ARCH_SOPHGO][lk-2]: Refer to the upstream code and change `SOC_FOO` to `ARCH_FOO` to facilitate back-porting of the code to the sg2042-dev branch during the upstrea
同上

2023-11-17 13:09 UTC, XieJiSS commented on newsletters/017.cn.md
> +  + [RISC-V: convert SOC_SOPHGO to ARCH_SOPHGO][lk-2]: 参考 upstream 的代码将 `SOC_FOO` 改为 `ARCH_FOO`，方便 upstream 过程中代码反向移植到 sg2042-dev 分支。
我感觉这里或许用 SOC_\* 改为 ARCH_\* 会更好理解一些？

2023-11-17 14:13 UTC, XieJiSS requested changes

2023-11-17 14:13 UTC, XieJiSS commented on newsletters/017.cn.md
> +  + [[PATCH 0/5] riscv: sophgo: add clock support for sg2042][lk-1]: 为 SG2942 添加 clock 支持，第一版。
typo

2023-11-17 14:13 UTC, XieJiSS commented on newsletters/017.md
> +  + [[PATCH 0/5] riscv: sophgo: add clock support for sg2042][lk-1]: Add clock support for SG2942, version 1.
typo

2023-11-18 05:00 UTC, unicornx commented
已经根据 comments 更新并重新提交了，请 merge。谢谢

2023-11-20 07:28 UTC, XieJiSS approved these changes
LGTM, thanks!

2023-11-20 07:28 UTC, merged